version: '2'
services:
  openssl:
    image: svagi/openssl:latest
    container_name: openssl
    entrypoint:
     - openssl
     - req
     - -newkey
     - rsa:2048
     - -days
     - "365"
     - -nodes
     - -x509
     - -config
     - tmp/conf/tls.conf
     - -extensions
     - v3_ca
     - -keyout
     - tmp/conf/nginx.key
     - -out
     - tmp/conf/nginx.crt
  
  bot_app:
    build: ./botapp
    privileged: true
    container_name: bot_app
    command: tail -F anything
    
  database:
    image: postgres:9.4
    container_name: postgres_database

  conjur:
    image: cyberark/conjur
    container_name: conjur_server
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]

  proxy:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8443:443"
    depends_on: [ conjur ]

  client:
    build: ./client
    container_name: conjur_client
    depends_on: [ proxy ]
    entrypoint: sleep
    command: infinity

